### ISSUE TITLE
visualise change in sentiments over time

### ISSUE THREAD

**Issue by milanwiedemann** [CDU-data-science-team/experiencesdashboard#10]
currently I visualise the density (which is affected by the number of responses during a specific time period). @ChrisBeeley  suggested to visualise proportions instead.

**Comment by milanwiedemann** [comment]
after spending some hours looking at your approach, I dont really think this works because it doesnt allow to calculate proportions based on grouping variables and I dont see how this could be implemented

**Comment by milanwiedemann** [comment]
I think it only makes sense to implement this if it's possible to show proportions for different groups, e.g., by division, or category

**Comment by milanwiedemann** [comment]
@ChrisBeeley  wrote some code with rolling means

https://github.com/CDU-data-science-team/experiencesdashboard/blob/a30b16891f5e708d045a33760e1c72e0c6e2846f/dev/00-scratchpad.Rmd#L45

but there might also be other ways of getting the same plot that we should explore

https://github.com/CDU-data-science-team/experiencesdashboard/blob/a30b16891f5e708d045a33760e1c72e0c6e2846f/dev/00-scratchpad.Rmd#L104

**Comment by milanwiedemann** [comment]
not super important at the moment because we also need to run this past users to see if it's actually something other people find helpful in understanding the data ... but in general this is quite a good way to describe our data so we should find a good solution

**Comment by ChrisBeeley** [comment]
Closed by #69
