### ISSUE TITLE
Sanitise all SQL operations

### ISSUE THREAD

**Issue by ChrisBeeley** [CDU-data-science-team/experiencesdashboard#101]
Sanitise SQL operations that come about from user input

**Comment by asegun-cod** [comment]
The goal is to prevent SQL injection vulnerabilities and ensure database safety. 

The current approach taken is to construct and parameterize  queries whenever raw SQL is called.

**Comment by ChrisBeeley** [comment]
Likely handled safely by DBI::dbWriteTable
