### ISSUE TITLE
Add overlapping topics visualisation

### ISSUE THREAD

**Issue by ChrisBeeley** [CDU-data-science-team/experiencesdashboard#105]
Some kind of visual or identification of where sub-topics overlap so can go and explore interactions further i.e., by looking at the individual comments which are mapped to the same two themes where there appears to be a relationship

**Comment by ChrisBeeley** [comment]
Example code https://github.com/ChrisBeeley/naturallanguageprocessing/tree/master/tag_bigrams

(note that the data is included and it should run out of the box OK)

**Comment by asegun-cod** [comment]
when you mean sub-topic are you talking about comment types or categories?

**Comment by asegun-cod** [comment]
see the solution in https://github.com/CDU-data-science-team/experiencesdashboard/blob/4527772f89fe3a0aa8a029d3c6a06c17448b013c/www/feedback_analysis.Rmd#L116
