### ISSUE TITLE
Graphs do not reset when you change your team/ date selection

### ISSUE THREAD

**Issue by ChrisBeeley** [CDU-data-science-team/experiencesdashboard#115]
Both the themes plot and the overlap plot are both interactive, and you can click them to see more comments. Unlike the previous tabular implementation of these features the selection is not forgotten if you reselect a different team or area- so for example if you select staff it will still be selected when you change team.

Investigate if this behaviour is undesirable to users and if so then change it

**Comment by asegun-cod** [comment]
The overlap plot has been removed. so this is no longer an issue
