### ISSUE TITLE
Ensure SPC graphs are only shown with at least 10 points of data

### ISSUE THREAD

**Issue by ChrisBeeley** [CDU-data-science-team/experiencesdashboard#116]
SPC charts should not be shown unless there is at least 10 points of data across the timescale, and there shouldn't be any gaps in the data (e.g. there is data for May and July but not for June). 

Only print SPC graphs with at least 10 points of data and no gaps

**Comment by asegun-cod** [comment]
I have switched to the `NHSRplotthedots::ptd_spc()` function for plotting the SPC chart to conform with the NHSI 'plot the dots' logic.
