### ISSUE TITLE
Add interactivity to upset plot

### ISSUE THREAD

**Issue by ChrisBeeley** [CDU-data-science-team/experiencesdashboard#13]
I was thinking an obvious improvement to the upset plot would be interactivity. Clicking on it would either bring up the relevant comments or flick to the comment tab and pre populate the controls to show those sentiments.

Interactivity seems difficult/ impossible (?) with UpsetR and ggupset but looks simple with {upsetjs} https://cran.r-project.org/web/packages/upsetjs/

I don't really understand upset plots but if you can plot it with upsetjs I can handle the interactivity?

**Comment by asegun-cod** [comment]
This re quire some extensive javascript code. a workaround is to have separate selectinput to interact with the variables as implement in #144
