### ISSUE TITLE
Improve upset plot 

### ISSUE THREAD

**Issue by ChrisBeeley** [CDU-data-science-team/experiencesdashboard#151]
Move selectors above the plot so the comment table can be seen at the same time as the plot

**Comment by asegun-cod** [comment]
There is a pending issue where the upset plot, which is showing off the page on a smaller screen, but it does come out ok on a larger screen. how can I resize it to fit any screen.
here is the code base
`plot function` https://github.com/CDU-data-science-team/experiencesdashboard/blob/6486af663868a3fc22ed51796a0bd669a6df065d/R/golem_utils_server.R#L224
`UI` https://github.com/CDU-data-science-team/experiencesdashboard/blob/6486af663868a3fc22ed51796a0bd669a6df065d/R/mod_overlap_1.R#L158

**Comment by asegun-cod** [comment]
Guess the resolution of Action 19 here [ed0c136](https://github.com/CDU-data-science-team/experiencesdashboard/pull/197/commits/ed0c136c9c2eee6e7a5019400e9d35497971c12d) can close this issue

**Comment by asegun-cod** [comment]
Closed by #197
