### ISSUE TITLE
SPC for FFT question

### ISSUE THREAD

**Issue by ChrisBeeley** [CDU-data-science-team/experiencesdashboard#17]
Lots of trusts seem to have SPC charts for the ticky box FFT question (although ours doesn't). We should add it as an option.

For the purposes of the repo we can make fake FFT data because we don't need to publish actual FFT data on here

**Comment by milanwiedemann** [comment]
@ChrisBeeley let's talk about this in next meeting, want to clarify what you mean

**Comment by milanwiedemann** [comment]
@ChrisBeeley I think we forgot to talk about this. I'll try to figure this out by myself, if I cant find the data you'll hear me shout for help

**Comment by ChrisBeeley** [comment]
Closed by #24 , but it's very imperfect. I'll file another issue after meeting with the customers to refine what we need to do with it
