### ISSUE TITLE
Error checking in reports

### ISSUE THREAD

**Issue by ChrisBeeley** [CDU-data-science-team/experiencesdashboard#175]
E.g. too many ethnic or age categories, and FFT points that are not based on a sufficient number of observations

[CustomReport_2023-08-04.docx](https://github.com/CDU-data-science-team/experiencesdashboard/files/12260156/CustomReport_2023-08-04.docx)

**Comment by asegun-cod** [comment]
To clarify, we will only create an SPC chart if there are a minimum of 10 data points and each data point has a minimum of 10 observations. For instance, if we are grouping data by month, we require at least 10 months of data and each month must have at least 10 comments. This is to guarantee that the data is somewhat representative of the population.
