### ISSUE TITLE
Add simple downloadable reports

### ISSUE THREAD

**Issue by ChrisBeeley** [CDU-data-science-team/experiencesdashboard#18]
#7 references reports but is quite a complicated implementation of them in the 0.3 release. We need some simple reports in the 0.2 release so the partner trusts can use and review example reports.

They could just consist of:
* an SPC for the FFT question (see #17 )
* A table summarising the % of each theme
* A table summarising the +ve -ve level of criticality/ sentiment
* Maybe a table that cross tabs theme and criticality/ sentiment

It will kick off a conversation even if it's not quite what they want

**Comment by milanwiedemann** [comment]
this can be a first implementation of the bigger goal of this issue https://github.com/CDU-data-science-team/experiencesdashboard/issues/7

**Comment by ChrisBeeley** [comment]
Closed by #26
