### ISSUE TITLE
Word clouds

### ISSUE THREAD

**Issue by ChrisBeeley** [CDU-data-science-team/experiencesdashboard#19]
Everyone loves word clouds :smile: 

(well, most people do :wink: )

Let's include word clouds somewhere too

**Comment by milanwiedemann** [comment]
check https://github.com/lepennec/ggwordcloud

**Comment by milanwiedemann** [comment]
also this package https://github.com/Lchiffon/wordcloud2

**Comment by milanwiedemann** [comment]
here is another approach that looks promising https://github.com/jbkunst/d3wordcloud

**Comment by ChrisBeeley** [comment]
This is not super important but it may be more fun than messing around with the MySQL database
