### ISSUE TITLE
make these inputs generic 

### ISSUE THREAD

**Issue by milanwiedemann** [CDU-data-science-team/experiencesdashboard#2]
probably not a good idea to hardcode all of these input boxes, check with @ChrisBeeley 

https://github.com/CDU-data-science-team/experiencesdashboard/blob/9e1a55b1410abba6e98bb2445e7f9cc60deabe7a/R/mod_sentiment.R#L31

https://github.com/CDU-data-science-team/experiencesdashboard/blob/9e1a55b1410abba6e98bb2445e7f9cc60deabe7a/R/mod_sentiment.R#L50

https://github.com/CDU-data-science-team/experiencesdashboard/blob/9e1a55b1410abba6e98bb2445e7f9cc60deabe7a/R/mod_sentiment.R#L95

**Comment by ChrisBeeley** [comment]
I'm fixing this as I go, okay to close now
