### ISSUE TITLE
find a better word for criticality

### ISSUE THREAD

**Issue by milanwiedemann** [CDU-data-science-team/experiencesdashboard#22]
this wording is confusing because we use it in the positive (what was good) and negative (what could be done better) context. 

something like "weighting" or "importance" might be better, let's discuss @ChrisBeeley @andreassot10

**Comment by andreassot10** [comment]
To begin with, not clear to me what this variable measures exactly. I recall someone from the trusts mentioning it's more about "criticism" than about how "critical" a comment is. @ChrisBeeley?

**Comment by ChrisBeeley** [comment]
Yes, it's the amount of criticism, if you like. We nicked it from Care Opinion but they actually don't use it on positive, only negative, so it works better for them. Maybe there isn't one word. Maybe we need to call it positivity/ negativity or something like that. I think we need to keep asking non data-y people what they think. Or maybe @Analyst-In-The-Wild or @Lextuga007 have some ideas we could use?

**Comment by Analyst-In-The-Wild** [comment]
Isn't it patient's opinion? or the patients comments? which are more neutral and allow for them to go either way

**Comment by ChrisBeeley** [comment]
So we have three things for each comment:

* Theme
* Sentiment (anger, happiness, sadness, etc.)
* "Criticality"- meaning negative comments have high criticality (+5, e.g.) and negative comments have large negative criticality (-5, e.g.). Although in the data we often call negative -5 and positive +5, which just confuses things further

We're looking for a word that means "Overall, is this comment expressing a positive opinion about a service or a negative one?"

**Comment by Analyst-In-The-Wild** [comment]
Expressiveness?
Weighting - as Milan suggested?
Directionality?
Significance?
Impactfulness (how much has the +/- experience impacted the patient)

**Comment by ChrisBeeley** [comment]
I'm moving this to 0.3.0 because this is probably the hardest thing in the whole project! :joy:

**Comment by ChrisBeeley** [comment]
This problem will be discussed by philosophers in hundreds of years, for now I am closing :laughing:
