### ISSUE TITLE
Produce a better search tool

### ISSUE THREAD

**Issue by ChrisBeeley** [CDU-data-science-team/experiencesdashboard#28]
Improve text searching- allow multiple selections, excluding text, and maybe a semantic search (this could even use document vectors if we want to get really clever)

**Comment by ChrisBeeley** [comment]
Note that semantic search is covered in #12

**Comment by asegun-cod** [comment]
add keywords search using regex wildcard and stemming https://github.com/CDU-data-science-team/experiencesdashboard/pull/144/commits/9229b783298e85f172f99a0ee6b77fda6283afbc
