### ISSUE TITLE
Broken the little coloured pills on the reactable

### ISSUE THREAD

**Issue by ChrisBeeley** [CDU-data-science-team/experiencesdashboard#38]
Changing the range of the criticality variable has broken the nice little coloured pills on the reactable 

![image](https://user-images.githubusercontent.com/1259867/111904975-5a742300-8a41-11eb-8805-cbe151de9980.png)

I did try to fix but I don't really understand the code, can you show me please?

**Comment by milanwiedemann** [comment]
Yes, the colours are defined in a css file that is located in this path experiencesdashboard/www/crit-table.css (this is where you fixed the path so it can run on the server I think):

- https://github.com/CDU-data-science-team/experiencesdashboard/blob/447f351aaad5081a9d389b303d68e3748138e455/www/crit-table.css

The .css file gets loaded at the top of the module:
https://github.com/CDU-data-science-team/experiencesdashboard/blob/43e92969baec5d3c57a15f0d4ceb0112757065e4/R/mod_category_criticality.R#L17-L18

Here is where I define the class:
https://github.com/CDU-data-science-team/experiencesdashboard/blob/43e92969baec5d3c57a15f0d4ceb0112757065e4/R/mod_category_criticality.R#L209

I think that all I need to do to fix this is to add two more colours for each table in the .css file:

- `tag crit-best-4`
- `tag crit-best-5`

and 

- `tag crit-imp-4`
- `tag crit-imp-5`

**Comment by ChrisBeeley** [comment]
Aha! Got it, thanks 😃

**Comment by ChrisBeeley** [comment]
Closed by #59
