### ISSUE TITLE
Add GitHub link to the dashboard

### ISSUE THREAD

**Issue by ChrisBeeley** [CDU-data-science-team/experiencesdashboard#47]

**Comment by Lextuga007** [comment]
Did this get coded into another app @ChrisBeeley and @andreassot10?

**Comment by ChrisBeeley** [comment]
@andreassot10 did it here https://github.com/CDU-data-science-team/pxtextminingdashboard/blob/80203b0a6268fd94523031b62c4659d0a0a9e530/R/app_ui.R#L17 but I didn't love his solution really. I thought you might have a whizzy HTML way of going it. Don't worry if you don't, I'll just copy Andreas's

**Comment by Lextuga007** [comment]
I'll have a look as I've been working with HTML today, it's just knowing where you want it in the Shiny apps.

**Comment by ChrisBeeley** [comment]
Closed by #64

**Comment by Lextuga007** [comment]
I was given the following code for a logo in Shiny which I was going to try but you closed this - do you no longer want a logo?:

```
tags$script(HTML("var header = $('.navbar > .container-fluid');
header.append('<div style=\"float:right\"><img src=\"ELC logo.jpg\" alt=\"alt\" style=\"float:right;width:280px;height:100px;padding-top:0px;\"> </a>`</div>');
console.log(header)"))
```

**Comment by ChrisBeeley** [comment]
I've added one now- have a look

**Comment by Lextuga007** [comment]
I saw it flash up (given my ongoing issue!) and it looked like a corner logo which looks nice!
