### ISSUE TITLE
add module for processing input data and help set up ui

### ISSUE THREAD

**Issue by milanwiedemann** [CDU-data-science-team/experiencesdashboard#5]
I haven't thought about it in detail but I think we need a separate data module that does all this stuff- looks at the data in the application and figures out what everything is, what the date column is, where the location columns are, what they're called and how many there are, all that stuff. The data module can feed the other modules data as well as meta data (number of columns, number of categories...)

_Originally posted by @ChrisBeeley in https://github.com/CDU-data-science-team/experiencesdashboard/issues/2#issuecomment-763797326_

**Comment by ChrisBeeley** [comment]
I've started on something else a bit smaller for some staff data and I think I will build part of the data module in that work.

The data module will output a dataframe with:

* 0 or more free text boxes
    * with 0 or more theme categories 
    * with 0 or more criticality categories
* 0 or more location variables
* 0 or 1 date variables
* 0 or more Likert type questions

I was wondering about the structure. Might be better as a dataframe containing list variables in some places. So each free text question would be a list like this:
question1 <- list(
  text = "This is the actual text",
  code1 = "XX",
  code2 = "CC",
  ...[arbitrary number of category codes]
  crit = n where -5 <= n <= 5
)

Then we could write modules that are capable of processing dataframes defined in this way, as long as we pass them a few lookup tables for Question names, theme categories, and criticality levels.

Any thoughts @milanwiedemann ?

**Comment by ChrisBeeley** [comment]
Incidentally @milanwiedemann I'm going to try to build the data module so that it runs live off the pinned data, pulling in the data as needed (based on the date range selected) rather than pulling all 10 years through which is what it does now. This may be hideously unstable or slow, but may as well give it a try and see what happens, and it may be useful elsewhere like with clinical data

**Comment by ChrisBeeley** [comment]
This is pretty large and complicated and depends on work elsewhere. It's not as necessary for prototyping as I thought it was. I'm going to move it to 0.3.0 so it doesn't hold things up

**Comment by ChrisBeeley** [comment]
Sort of closed enough by #50
