### ISSUE TITLE
generate customisable reports   

### ISSUE THREAD

**Issue by milanwiedemann** [CDU-data-science-team/experiencesdashboard#7]
I'd like to be able to generate customisable reports in the app:

  1. first make some selections (e.g. date range, division, ...) 
  1. then apply all these selections to differents parts of the shiny app that the user selects e.g., 
 
  - user1 selects these elements from the shiny app
     - generate table from tab1 (e.g. patient experiences)
     - generate plot from tab2 (e.g. staff experiences)
     - generate text summarising tab3 (e.g. complaints)

  - user2 selects these elements from the shiny app
     - generate plot from tab1 (e.g. patient experiences)
     - generate table from tab2 (e.g. staff experiences)
     - generate text summarising tab4 (e.g. compliments)

do you think this is a good idea @ChrisBeeley ? and do you think it's possible?

**Comment by milanwiedemann** [comment]
this package might be useful https://github.com/rundel/parsermd

https://rstudio.com/resources/rstudioglobal-2021/parsermd-parsing-r-markdown-for-fun-and-profit/

**Comment by ChrisBeeley** [comment]
Following functionality to be built (most content optional, report modular):

- [ ] Date range- qly, yearly, custom date range
- [ ] Give total response numbers and individual team numbers
- [ ] FFT scores and graph
- [ ] Summary of %s of each theme
- [ ] Verbatim comments, optionally a subset tagged to a theme
- [ ] Any plot
- [ ] Demographic characteristics of sample
- [ ] Comparison of FFT scores across demographics

**Comment by ChrisBeeley** [comment]
Links to #91
