### ISSUE TITLE
Ensure only stable SPC points are shown

### ISSUE THREAD

**Issue by ChrisBeeley** [CDU-data-science-team/experiencesdashboard#74]
Sometimes SPC charts are drawn with very few points of data for some dates, with the result that the number is very different from the average. Remove such points

**Comment by ChrisBeeley** [comment]
Refers to this plot: https://github.com/CDU-data-science-team/experiencesdashboard/blob/15676f4aa6b9b609bac8296983268b829e7f04fa/R/mod_fft.R#L25

**Comment by ChrisBeeley** [comment]
Relevant code here

**Comment by asegun-cod** [comment]
The proposed solution in  e6f338a filters out all groups/dates with less than 20 values. This might result in us having fewer than 3 groups/dates and an empty plot is returned in this case.

**Comment by ChrisBeeley** [comment]
You may be planning this anyway but please add a message that tells the user why the graph is not shown
