### ISSUE TITLE
Demographic panel is not handled intelligently

### ISSUE THREAD

**Issue by ChrisBeeley** [CDU-data-science-team/experiencesdashboard#88]
At the moment the dashboard makes strong assumptions about the existence of demographic data. Add a method of checking if it exists at all and if it does what is there

**Comment by ChrisBeeley** [comment]
Maybe we could leave this until we've seen actual data from the pilot sites?

**Comment by asegun-cod** [comment]
a pilot solution has been made at [cea73b7](https://github.com/CDU-data-science-team/experiencesdashboard/commit/cea73b76aa751532d03dcf954f8b9f4361e400be)
This might change based on the data we get from the pilot trusts
